COMPILER = g++
FLAGS = -std=c++11 -Wall -O3 -funroll-loops -ftree-vectorize

all:
	#$(COMPILER) $(FLAGS) StandardIfTree.h StandardIfTree.cpp testStandardIfTree.cpp -o testStandardIfTree
	#$(COMPILER) $(FLAGS) OptimizedPathIfTree_128000.h OptimizedPathIfTree_128000.cpp testOptimizedPathIfTree_128000.cpp -o testOptimizedPathIfTree_128000
	#$(COMPILER) $(FLAGS) OptimizedPathIfTree_384000.h OptimizedPathIfTree_384000.cpp testOptimizedPathIfTree_384000.cpp -o testOptimizedPathIfTree_384000
	#$(COMPILER) $(FLAGS) NaiveNativeTree.h NaiveNativeTree.cpp testNaiveNativeTree.cpp -o testNaiveNativeTree
	#$(COMPILER) $(FLAGS) StandardNativeTree.h StandardNativeTree.cpp testStandardNativeTree.cpp -o testStandardNativeTree
	#$(COMPILER) $(FLAGS) OptimizedNativeTree_25.h OptimizedNativeTree_25.cpp testOptimizedNativeTree_25.cpp -o testOptimizedNativeTree_25
	$(COMPILER) $(FLAGS) OptimizedNativeForest_25.h OptimizedNativeForest_25.cpp testOptimizedNativeForest_25.cpp -o testOptimizedNativeForest_25
